# SonarCloud Configuration
# https://sonarsource.github.io/sonarcloud/
sonar.organization=victron-venus
sonar.projectKey=victron-venus_inverter-dashboard-vue
sonar.sources=src
sonar.exclusions=src/i18n/**,src/static/**,**/*.test.ts
sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/i18n/**